export const cliOptions = [
    {
        groupName: "Server",
        description: "Run the Server",
        options: [
            { key: "-d", name: "database", description: "Database(s) used when installing or updating modules." },
            { key: "-i", name: "init", description: "Modules to install before running the server (requires -d)." },
            { key: "-u", name: "update", description: "Modules to update before running the server." },
            { key: "--reinit", name: "reinit", description: "Modules to reinitialize before starting the server." },
            { key: "--upgrade-path", name: "upgrade-path", description: "Directories from which additional upgrade scripts are loaded." },
            { key: "--pre-upgrade-scripts", name: "pre-upgrade-scripts", description: "Upgrade scripts that run before loading base module." },
            { key: "--load", name: "load", description: "List of server-wide modules to load." },
            { key: "-c", name: "config", description: "Path to an alternate configuration file." },
            { key: "-D", name: "data-dir", description: "Directory path to store Odoo data." },
            { key: "-s", name: "save", description: "Save the server configuration to the config file." },
            { key: "--with-demo", name: "with-demo", description: "Install demo data in new databases." },
            { key: "--without-demo", name: "without-demo", description: "Do not install demo data (default)." },
            { key: "--skip-auto-install", name: "skip-auto-install", description: "Skip auto-installing modules." },
            { key: "--pidfile", name: "pidfile", description: "Path where the server PID will be stored." },
            { key: "--stop-after-init", name: "stop-after-init", description: "Stop the server after initialization." },
            { key: "--geoip-city-db", name: "geoip-city-db", description: "Path to the GeoIP City database file." },
            { key: "--geoip-country-db", name: "geoip-country-db", description: "Path to the GeoIP Country database file." },
            { key: "--db_replica_host", name: "db_replica_host", description: "Replica database host." },
            { key: "--db_replica_port", name: "db_replica_port", description: "Replica database port." },
            { key: "--db-filter", name: "db-filter", description: "Regex filter limiting database visibility." },
            { key: "--db-template", name: "db-template", description: "Template used when creating new databases." },
            { key: "--pg_path", name: "pg_path", description: "Path to PostgreSQL binaries." },
            { key: "--no-database-list", name: "no-database-list", description: "Suppress database listing." },
            { key: "--db_sslmode", name: "db_sslmode", description: "Control SSL security mode with PostgreSQL." },
            { key: "--unaccent", name: "unaccent", description: "Enable unaccent extension when creating databases." },
        ],
    },
    {
        groupName: "Advanced Dev",
        description: "Developer & advanced server flags",
        options: [
            { key: "--dev", name: "dev", description: "Enable dev features (xml,reload,qweb,...)." },
            { key: "--no-http", name: "no-http", description: "Disable HTTP workers." },
            { key: "--http-interface", name: "http-interface", description: "HTTP interface address." },
            { key: "-p", name: "http-port", description: "HTTP port." },
            { key: "--proxy-mode", name: "proxy-mode", description: "Enable proxy mode." },
            { key: "--x-sendfile", name: "x-sendfile", description: "Use X-Sendfile header." },
        ],
    },
    {
        groupName: "Email",
        description: "Outgoing email configuration",
        options: [
            { key: "--email-from", name: "email-from", description: "Default FROM email address." },
            { key: "--from-filter", name: "from-filter", description: "Filter for outgoing mail servers." },
            { key: "--smtp", name: "smtp", description: "SMTP server address." },
            { key: "--smtp-port", name: "smtp-port", description: "SMTP server port." },
            { key: "--smtp-ssl", name: "smtp-ssl", description: "Enable SSL/STARTTLS for SMTP." },
            { key: "--smtp-user", name: "smtp-user", description: "SMTP username." },
            { key: "--smtp-password", name: "smtp-password", description: "SMTP password." },
            { key: "--smtp-ssl-certificate-filename", name: "smtp-ssl-certificate-filename", description: "SSL certificate file for SMTP." },
            { key: "--smtp-ssl-private-key-filename", name: "smtp-ssl-private-key-filename", description: "SSL private key file for SMTP." },
        ],
    },
    {
        groupName: "Internationalisation",
        description: "Language & translation options",
        options: [
            { key: "--load-language", name: "load-language", description: "Languages to load." },
            { key: "--i18n-overwrite", name: "i18n-overwrite", description: "Overwrite existing translations." },
        ],
    },
    {
        groupName: "Logging",
        description: "Logging configuration",
        options: [
            { key: "--logfile", name: "logfile", description: "Log output to a file." },
        ],
    },
    {
        groupName: "Multiprocessing",
        description: "Workers & performance tuning",
        options: [
            { key: "--workers", name: "workers", description: "Number of HTTP workers." },
            { key: "--limit-request", name: "limit-request", description: "Max requests per worker." },
            { key: "--limit-memory-soft", name: "limit-memory-soft", description: "Soft memory limit in bytes." },
            { key: "--limit-memory-hard", name: "limit-memory-hard", description: "Hard memory limit in bytes." },
            { key: "--limit-time-cpu", name: "limit-time-cpu", description: "CPU time limit per request." },
            { key: "--limit-time-real", name: "limit-time-real", description: "Real time limit per request." },
            { key: "--max-cron-threads", name: "max-cron-threads", description: "Number of cron threads." },
            { key: "--limit-time-worker-cron", name: "limit-time-worker-cron", description: "Time limit for cron workers." },
        ],
    },
];
